version: '3'

tasks:
  :build:
    cmds:
      - 'go build -o dist/main ./cmd/**.go'
    sources:
      - ./*.go,
      - ./**/*.go

  :start:
    cmds:
      - task: :build
      - './dist/main'
    sources: 
      - ./cmd/**.go,
      -  ./cmd/**.go,